import Head from "next/head";
import React from "react";
import type { GetServerSidePropsContext } from "next";
import type { Stripe } from "stripe";

type Props = {
  data: {
    invoice: {
      amount_paid: number;
    };
  };
};

export default function Home(props: Props) {
  // useEffect(() => {
  //   const invoices = listInvoices();
  // }, []);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-4">
        {props.data.invoice.amount_paid > 0 ? (
          <span className="rounded-full border-2 border-green-700 bg-green-400 p-4 font-bold text-white">
            Invoice paid ✅
          </span>
        ) : (
          <span className="rounded-full border-2 border-red-700 bg-red-400 p-4 font-bold text-white">
            Invoice unpaid ❌
          </span>
        )}
      </main>
    </>
  );
}

export const getServerSideProps = async (
  context: GetServerSidePropsContext,
) => {
  const { query } = context;
  const { id } = query;

  const invoice = await fetch(
    `https://stripe-embeds.vercel.app/api/invoice/${id as string}`,
  );

  const json = (await invoice.json()) as { invoice: Stripe.Invoice };

  const data = {
    invoice: {
      amount_paid: json.invoice.amount_paid,
    },
  };

  console.log(data);
  return {
    props: {
      data,
    },
  };
};
