import Head from "next/head";
import React from "react";
import { getApiUrl } from "../../utils/apiUrl";

type Props = {
  data: any;
};

export default function Home(props: Props) {
  // useEffect(() => {
  //   const invoices = listInvoices();
  // }, []);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-4">
        {props.data.invoice.amount_paid > 0 ? (
          <span className="rounded-full border-2 border-green-700 bg-green-400 p-4 font-bold text-white">
            Invoice paid ✅
          </span>
        ) : (
          <span className="rounded-full border-2 border-red-700 bg-red-400 p-4 font-bold text-white">
            Invoice unpaid ❌
          </span>
        )}
      </main>
    </>
  );
}

export const getServerSideProps = async (context) => {
  const { query } = context;
  const { id } = query;

  const invoice = await fetch(getApiUrl(`/api/invoice/${id}`));

  const data = await invoice.json();

  console.log(data);
  return {
    props: {
      data,
    },
  };
};
