import Head from "next/head";
import React from "react";
import type { GetServerSidePropsContext } from "next";

type Props = {
  code: string;
};

export default function AuthRedirect(props: Props) {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-4">This your code? {props.code}</main>
    </>
  );
}

export const getServerSideProps = async (
  context: GetServerSidePropsContext,
) => {
  const { query } = context;
  const code = query.code;

  return {
    props: {
      code: code ? code : "",
    },
  };
};
