import Head from "next/head";
import Link from "next/link";

export default function Home() {
  // useEffect(() => {
  //   const invoices = listInvoices();
  // }, []);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Stripe <span className="text-[hsl(280,100%,70%)]">Embeds</span>
          </h1>
          <div className="flex justify-center">
            <a
              className="rounded-xl bg-indigo-400 p-4 text-center font-bold text-white"
              href="https://connect.stripe.com/oauth/authorize?response_type=code&client_id=ca_KWtyB62rwhbFee4tui0LjrCeydstyDz0&scope=read_write&redirect_uri=https://stripe-embeds.vercel.app/auth-redirect"
            >
              Login with Stripe
            </a>
          </div>
        </div>
      </main>
    </>
  );
}
